### ISSUE TITLE
关于方法的一些问题

### ISSUE THREAD

**Issue by orangYZC** [chenydong/PA-Diff#6]
似乎你们的主要创新点在physical_fn，从GaussianDiffusion.p_losses我们可以看到损失函数
`p_a ,p_t = self.physical_fn(x_in['SR'])`
`phy_out = x_in['HR'] * p_t + (1 - p_t) * p_a`
`loss2 = self.loss_func_ph2(phy_out, x_in['SR'])`
phy_out可以视作一个损失函数，监督目标是x_in['SR']，但是作为一种监督学习，你们在physical_fn的输入中就给到了监督目标x_in['SR']，所以很容易网络就会学习到
`p_a = x_in['SR'] & p_t = 0`
当p_t = 0时你们的这个物理模型创新点就没有意义了

另外一个创新点
`nrn_out = self.nrn_fn(x_in['SR'])`
`condition_x = torch.concat([p_a,generate_gt+nrn_out],dim=1)`
`loss3 = self.loss_func_nrn(nrn_out, x_in['HR'])`
nrn_fn的输入是x_in['SR']，监督目标是x_in['HR']即GT，所以你们期望在输入扩散模型前，nrn_fn(input)就把一部分条件学习到接近于GT
扩散模型学习的是在Input作为condition的条件下GT的分布规律，但是你们的方法把(input，nrn_fn(input))作为条件给到扩散模型
nrn_fn(input)已经被监督学习到近似于GT，那扩散模型就会严重依赖这部分已经被nrn_fn处理的数据，学习Input到GT的分布规律的任务也不会交给扩散模型来执行了
这可能也是你们方法性能较低的原因，UIEB数据集上的256x256尺寸上PSNR仅21.56，但是DM-water的PSNR实际上我们复现可以达到27-28左右，你们的方法似乎在让水下图像增强领域的性能倒退

**Comment by ChenzhaoNju** [comment]
> 似乎你们的主要创新点在physical_fn，从GaussianDiffusion.p_losses我们可以看到损失函数 `p_a ,p_t = self.physical_fn(x_in['SR'])` `phy_out = x_in['HR'] * p_t + (1 - p_t) * p_a` `loss2 = self.loss_func_ph2(phy_out, x_in['SR'])` phy_out可以视作一个损失函数，监督目标是x_in['SR']，但是作为一种监督学习，你们在physical_fn的输入中就给到了监督目标x_in['SR']，所以很容易网络就会学习到 `p_a = x_in['SR'] & p_t = 0` 当p_t = 0时你们的这个物理模型创新点就没有意义了
> 
> 另外一个创新点 `nrn_out = self.nrn_fn(x_in['SR'])` `condition_x = torch.concat([p_a,generate_gt+nrn_out],dim=1)` `loss3 = self.loss_func_nrn(nrn_out, x_in['HR'])` nrn_fn的输入是x_in['SR']，监督目标是x_in['HR']即GT，所以你们期望在输入扩散模型前，nrn_fn(input)就把一部分条件学习到接近于GT 扩散模型学习的是在Input作为condition的条件下GT的分布规律，但是你们的方法把(input，nrn_fn(input))作为条件给到扩散模型 nrn_fn(input)已经被监督学习到近似于GT，那扩散模型就会严重依赖这部分已经被nrn_fn处理的数据，学习Input到GT的分布规律的任务也不会交给扩散模型来执行了 这可能也是你们方法性能较低的原因，UIEB数据集上的256x256尺寸上PSNR仅21.56，但是DM-water的PSNR实际上我们复现可以达到27-28左右，你们的方法似乎在让水下图像增强领域的性能倒退

非常感谢你的质疑。
问题1：关于物理分支，GT只参与损失函数的计算。至于创新的问题，我们的论文里已经说的很清楚了。
问题2：关于隐式神经表示分支。我们的论文里也说的很清楚。
问题3：关于性能。UIEB 690+200划分的数据集，很多论文都有，你可以找一下测测。我想要说明一下，我们这篇论文有两套代码，一套自己搭的，一套是以DM-water为codebase搭的。放到GitHub上的代码正是后者。这也是为了方便大家比较性能。我们和DM-water（包括Ushape）的性能比较，完全是一样的设置，正如论文中写的那样，非常公平比较。所以，你想要喷我们，你自己可以在LSUI（相比于UIEB，这个数据集更好）复现一下，请注意要相同的设置公平公平公平。根据我们的实验，我们的效果是要比DM-water好很多的。
PS:有什么问题你可以来问我，加我微信：15346593536.另外，我现在很忙，压力很大，wf-diff的code我闲下来的时候自然会整理并开源。

**Comment by orangYZC** [comment]
LSUI上啊，DM-water中写明了是在128x128上训练，在256x256上测试
然后你们把DM-water在LSUI上的结果27.65/0.8867搬过来跟你们256x256上训练的结果对比，既然在UIEB上有复现结果为什么LSUI上不用复现的结果呢，这就是你说的，设置公平公平公平吗？

但是在UIEB上把别人28.20/0.9429标成21.88/0.8194，真的很难不让人怀疑目的，
我已经大概知道为什么你们能把DM-water复现的这么差了，你们的网络参数做的太大了batch只能设置成2
然后在复现DM-water的时候也把他的batch调成了2
我们在把DM-watert的batch调成16，输入256x256的情况下能达到26.9544/0.9434
或者看一下这篇文章A Comprehensive Survey on Underwater Image Enhancement Based on Deep Learning
他们对所有方法做了benchmark，DM-water在他们的benchmark中UIEB23.03/0.9099，LSUI29.56/0.9194
但是因为你们的模型设计的不合理太大了，就能把别人小参数量的batch也降低到2吗？

首先还是对你们能中CVPR表达诚挚的敬意，但是中了CVPR也意味着要被很多双眼睛盯着
还是认真搞科研吧，起码在CVPR这个标志着领域最前沿的会议上，不要出现类似的数据上的瑕疵

**Comment by orangYZC** [comment]
另外，我从去年MM上DM-water发表开始就follow这个方法继续做更深一步的工作，对他的性能已经复现了很多遍了，也很清楚他的性能怎么样，LSUI、UFO、EUVP我们都复现了，复现很多遍了
只是看到DM-water在UIEB上被标这么低还是有些替这个方法有些愤懑，言辞上若有不妥，还请见谅

**Comment by Chengkai66** [comment]
佬们，我想问下这个hr是GT（空气中的真实图像），sr是像LSUI数据集里的input是吗

**Comment by orangYZC** [comment]
> 佬们，我想问下这个hr是GT（空气中的真实图像），sr是像LSUI数据集里的input是吗

是的，你要把LSUI的图片先全部resize到256x256，再输入网络

**Comment by Chengkai66** [comment]
这样啊，谢谢佬，我昨天在复现DM_water，用它里面的prepare.py处理的代码，跑完发现PSNR才18.几，我就感觉我数据集处理错了

**Comment by GraceZhuuu** [comment]
> > 佬们，我想问下这个hr是GT（空气中的真实图像），sr是像LSUI数据集里的input是吗
> 
> 是的，你要把LSUI的图片先全部resize到256x256，再输入网络

看到几片文章都是resize到256x256处理，那么计算指标时是resize到原尺寸还是将参考图resize到256x256呀，没有看到文章里有写

**Comment by crazyggg1** [comment]
我们在训练的时候，dm-underwater和pa-diff结果也不太稳定，存在统一的色偏。请问佬们遇到过吗？
@orangYZC @ChenzhaoNju 
![Image](https://github.com/user-attachments/assets/e5a78403-ea6f-4bda-8642-fe6d63e731f5)

![Image](https://github.com/user-attachments/assets/3b095196-c962-4661-85af-01629115c239)

**Comment by orangYZC** [comment]
> 我们在训练的时候，dm-underwater和pa-diff结果也不太稳定，存在统一的色偏。请问佬们遇到过吗？ [@orangYZC](https://github.com/orangYZC) [@ChenzhaoNju](https://github.com/ChenzhaoNju) ![Image](https://github.com/user-attachments/assets/e5a78403-ea6f-4bda-8642-fe6d63e731f5)
> 
> ![Image](https://github.com/user-attachments/assets/3b095196-c962-4661-85af-01629115c239)

存在色偏是训练时间不够，DM-water的训练时间3090单卡要接近3-5天才逐渐稳定，想要复现时间短点，就前期调大一点学习率加快收敛，后期调小学习率提升性能上限

**Comment by crazyggg1** [comment]
> > 我们在训练的时候，dm-underwater和pa-diff结果也不太稳定，存在统一的色偏。请问佬们遇到过吗？ [@orangYZC](https://github.com/orangYZC) [@ChenzhaoNju](https://github.com/ChenzhaoNju) ![Image](https://github.com/user-attachments/assets/e5a78403-ea6f-4bda-8642-fe6d63e731f5)
> > ![Image](https://github.com/user-attachments/assets/3b095196-c962-4661-85af-01629115c239)
> 
> 存在色偏是训练时间不够，DM-water的训练时间3090单卡要接近3-5天才逐渐稳定，想要复现时间短点，就前期调大一点学习率加快收敛，后期调小学习率提升性能上限

好的，感谢。我们batch size 3迭代950k也存在类似的色偏问题，感觉训练挺不稳定的。在相关的水下diffsuion工作中也看到过类似的反馈。

**Comment by orangYZC** [comment]
> > > 我们在训练的时候，dm-underwater和pa-diff结果也不太稳定，存在统一的色偏。请问佬们遇到过吗？ [@orangYZC](https://github.com/orangYZC) [@ChenzhaoNju](https://github.com/ChenzhaoNju) ![Image](https://github.com/user-attachments/assets/e5a78403-ea6f-4bda-8642-fe6d63e731f5)
> > > ![Image](https://github.com/user-attachments/assets/3b095196-c962-4661-85af-01629115c239)
> > 
> > 
> > 存在色偏是训练时间不够，DM-water的训练时间3090单卡要接近3-5天才逐渐稳定，想要复现时间短点，就前期调大一点学习率加快收敛，后期调小学习率提升性能上限
> 
> 好的，感谢。我们batch size 3迭代950k也存在类似的色偏问题，感觉训练挺不稳定的。在相关的水下diffsuion工作中也看到过类似的反馈。

我们是把训练数据下采样到256x256的分辨率上训练的，学习率1e-4，8个batch，100w个iters才开始稳定，到150w个iters才能达到最高性能，而且不同训练轮数之间也存在不稳定问题，我们是取了多个轮数中测得的最高值的，这是由于DM-water的网络结构设计存在一定的缺陷，我们在前一个工作里解决了这个问题，可惜一作被拿了，目前在投，导师还不允许挂arxiv

**Comment by crazyggg1** [comment]
> > > > 我们在训练的时候，dm-underwater和pa-diff结果也不太稳定，存在统一的色偏。请问佬们遇到过吗？ [@orangYZC](https://github.com/orangYZC) [@ChenzhaoNju](https://github.com/ChenzhaoNju) ![Image](https://github.com/user-attachments/assets/e5a78403-ea6f-4bda-8642-fe6d63e731f5)
> > > > ![Image](https://github.com/user-attachments/assets/3b095196-c962-4661-85af-01629115c239)
> > > 
> > > 
> > > 存在色偏是训练时间不够，DM-water的训练时间3090单卡要接近3-5天才逐渐稳定，想要复现时间短点，就前期调大一点学习率加快收敛，后期调小学习率提升性能上限
> > 
> > 
> > 好的，感谢。我们batch size 3迭代950k也存在类似的色偏问题，感觉训练挺不稳定的。在相关的水下diffsuion工作中也看到过类似的反馈。
> 
> 我们是把训练数据下采样到256x256的分辨率上训练的，学习率1e-4，8个batch，100w个iters才开始稳定，到150w个iters才能达到最高性能，而且不同训练轮数之间也存在不稳定问题，我们是取了多个轮数中测得的最高值的，这是由于DM-water的网络结构设计存在一定的缺陷，我们在前一个工作里解决了这个问题，可惜一作被拿了，目前在投，导师还不允许挂arxiv

跟您交流收益颇深，个人感觉对于Low-Level的任务训练时间过长、训练不稳定也是值得解决的问题，毕竟大家都会说diffusion比GAN训练更稳定，目前看来这点优势微乎其微，尤其是在low-level任务的应用上。

**Comment by FuhengZhou** [comment]
又看到你了大佬😂。   WF-DIFF的结果是指标问题。PSNR-Y的话和他们论文中的报告几乎是一致的。 
所以只能算是测试瑕疵。 

UIEB的问题 真的很玄学。 这个数据集我不知道28是怎么训练出来的。 不管我怎么划分 都是会过拟合。我们组最高只能跑到22左右测试集。所以我们组就没放这个数据集的结果。因为结果跟划分的有极大的关系。 

chongli大佬在AAAI2023上的文章的模型NU2Net可以到24（直接跑预训练权重）。 但是我认为如果不重新训练的话只跑预训练权重的话  还是不公平对比。因为LSUI和UIEB的GT在低频结果（整体色偏）上存在严重的差异。高频上没什么问题。 就比如U45的第一张图的潜水员和金属人。LSUI训练出来的跟UIEB训练出来的高频差异极低。但是低频差异极高。这也是我目前一直在研究的点。 就是由于GT图像背景色偏处理不完全引起的。

但是重新训练一样会有问题。作者的实验设置和设备差异也是个问题。 暂时没有很好的解决方法。 
Phaseformer，PA-diff， WF-DIFF和一篇最新的WACV的一篇都是每个训练集单独训练测试。所以我后期的文章也follow了这种方式。 之前一直是LSUI训练一个权重直接测试。但是我发现同样的模型 LSUI训练出的结果的UIQM UCIQE的指标比UIEB训练出来的低。 看大家（Phaseformer的代码库）都是哪个高用哪个。

DMunderwater 的性能我复现了。确实很高。（在WF-DIFF回复过您 当时没复现成功 是因为训练epoch需要加很多。作者给定的epoch数不够）  不管是使用给定预训练权重还是重新训练。但是不得不说作者代码写的。可修改性有点难崩。 

我感觉现大家好像都是每个数据集单独训练 单独测试。这可能以后会成为主流。
